wandb_version: 1

device:
  desc: null
  value: cpu
env_num:
  desc: null
  value: 2
facor_num:
  desc: null
  value: 40
reg_only_embed:
  desc: null
  value: true
reg_env_embed:
  desc: null
  value: false
batch_size:
  desc: null
  value: 8192
epochs:
  desc: null
  value: 100
cluster_interval:
  desc: null
  value: 5
evaluate_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.005
invariant_coe:
  desc: null
  value: 3.351991776096847
env_aware_coe:
  desc: null
  value: 9.988658447411407
env_coe:
  desc: null
  value: 9.06447753571379
L2_coe:
  desc: null
  value: 3.1351402017943117
L1_coe:
  desc: null
  value: 0.4935216278026648
alpha:
  desc: null
  value: 1.9053711444718746
use_class_re_weight:
  desc: null
  value: true
use_recommend_re_weight:
  desc: null
  value: false
test_begin_epoch:
  desc: null
  value: 0
begin_cluster_epoch:
  desc: null
  value: null
stop_cluster_epoch:
  desc: null
  value: null
top_k_list:
  desc: null
  value: '[3, 5, 7]'
test_batch_size:
  desc: null
  value: 1024
eval_k:
  desc: null
  value: 5
eval_metric:
  desc: null
  value: ndcg
random_seed:
  desc: null
  value: 0
'has_item_pool: ':
  desc: null
  value: false
cluster_use_random_sort:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711019899.829089
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.16.2
      8:
      - 1
      - 5
      13: darwin-x86_64
